drop table if exists shoppingList;
DROP type if exists groceryType;
CREATE TYPE groceryType as enum (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

CREATE TABLE shoppingList(
    id integer primary key generated by default as identity,
    name text not null,
    price numeric not null,
    date_added timestamp default now(),
    checked BOOLEAN default false,
    category groceryType not null
);